---
title: R Basics - Assessment 
author:
  name: Andreas Handel
  affiliation: University of Georgia
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
bibliography: ../../media/references.bib
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(error = TRUE, out.width = "100%")
tutorial_options(exercise.timelimit = 60)
```



##Overview
R, like any other (programming) language, can only be learned by using it. As such, the practice sections for R (and this course in general) are likely the most critical components helping you learn.



## R code example
* Get the file "TB_data_analysis_example.R" from eLC
* Open it in Rstudio
* Take a look at the code
* Run the whole thing pressing the source() button in the top-left of the code window
* Run it step by step with the "run" button, observe
* Play around a bit





## Instructions

Go to the discussion board for this module and post something answering these questions:

* Which part of the _'R Experience'_ so far did you find the most exciting?
* Which part of the _'R Experience'_ so far did you find the most frustrating/confusing?
* What topic(s) related to R do you want to see covered in this course?

You are also welcome to comment on other people's posts.

##Assessments check-list
The assessment for this module is based on:

* Your discussion contribution as described in the discussion document
* Your completion of the Datacamp courses assigned for this module






