---
title: MADA Fall 2019 - Course Introduction 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Introduction
Welcome to the class Modern Applied Data Analysis (MADA)! The course is listed as EPID8060/BIOS8060. It doesn't matter if you are enrolled under the EPID or BIOS label. I will refer to the course as MADA or EPID8060 interchangably. 

This somewhat long document will provide you with all the important information to know what to expect and to get started.

## Module Overview
This first unit (which in this course I call modules) provides an overview of the whole course. I first describe the objectives, goals, and my philosophy. That is followed by the logistical details of how everything will (hopefully) work. Finally, I end with a few motivating examples of real world data analyses that I hope you will be able to do once you complete the course.

## Module Learning Objectives
The specific learning objectives for this introductory module are:

* Know how this course is set up and what you are expected to do.
* Know what this course is all about.
* Know a bit about your classmates and the instructor.
* Get motivated toward learning and doing data science.



# Course Learning Objectives 

The main goal for this course is to teach the whole process of performing a data analysis project. This starts with identifying a suitable question-data pair, all the way to fitting statistical models and producing materials that communicate what you did and found. A second goal is to introduce you to some modern analysis approaches that these days often go by the name of 'Machine Learning'. Finally, a related third goal is to introduce you to a set of tools that allow for a modern, reproducible workflow of your analyis.

The specific learning objectives that I hope you will achieve by going through this course are:

* Given a data set, define the questions that can be answered and formulate and implement suitable analytic approaches.
* Given a data science question, determine the type of data and analytic approach needed to answer it.
* Know how to obtain, process and analyze data from a variety of different sources.
* Be able to thoughtfully and critically process and analyze data, question where the data comes from, what it means.
* Be knowledgeable about data types and standards and what analysis methods to apply to specific situations.
* Critically compare and evaluate the strengths and weaknesses of different modern data analysis approaches, judge the appropriateness of different approaches for specific questions and data sets.
* Explain the importance of workflow and project management tools and reproducibility for data analysis, and know how to use those tools.
* Be able to quickly learn how to use new software and tools, figure out how to get help when stuck, and make it work for you.
* Be familiar with different approaches that exist to analyze data, know how they work, their advantages and disadvantages, etc.
* Design and implement successful data analyses using state-of-the-art analysis software to translate data to information and knowledge that leads to actionable insights.
* Summarize analysis results in ways that provide actionable conclusions and that are easily understandable by different audiences, such as lay persons, decision makers, and expert colleagues.
* Critically assess any assumptions that go into any analysis approach, decide if they are justified and what they mean for the results.
* Learn to 'look yourself over the shoulder' and critically assess what you are doing, what assumptions you make by doing certain things, and if and how you can justify these.
* Understand the whole data analysis workflow/process.
* Be able to do a complete data analysis from beginning to end using real data.
* Be comfortable using R to do data analysis in a reproducible manner.
* Appraise different types of modern analytic approaches
* Critically compare and evaluate the strengths and weaknesses of different analytic approaches
* Formulate the appropriate analytic approach for a given data set
* Articulate a research question and outline a suitable analytic approach for a given data set
* Design and implement successful data analyses using a state-of-the-art analysis software
* Explain the importance of workflow management and reproducibility for successful data analysis
* Judge the usefulness of different analysis tools described in the primary research literature
* Evaluate state-of-the art analysis approaches from the research literature
* Assess the strengths and weaknesses of different approaches to representing the results of data analyses
* Summarize analysis results in a way that is easily understandable for different audiences, such as lay persons, decision makers, and expert colleagues




# Course Prerequisites

Nominally, for this course some R coding skills (e.g. as obtained in EPID 7500), as well as basic knowledge of statistics at the level of fitting linear or logistic models to data (e.g. as obtained in our BIOS 7010 and 7020 courses) are expected. If you don't have any of the pre-requisite R coding or statistics knowledge, you can still take the class, but you need to be prepared to spend some extra time and effort to fill any gaps. This will be especially true for the `R` coding part. There are likely some students in class who have pretty solid previous `R` experience, while others might have little to none. That means if you are in the latter category, expect to spend extra time getting up to speed with R. I believe it's doable and worth the effort, but you need to be prepared for it. For instance we'll spend a week on 'R Basics' - for those with good `R` knowledge, this might be a 2 hour refresher, for those with none that week might be a 20 hour committment. There will be plenty of help from myself, classmates and the internet if you end up getting stuck with some of the coding, but your effort and committment are still required.


# Course Philosophy
My dream class is one that operates as described in this quote by Seth Godin:

_"If you want people to become passionate, engaged in a field, transformed by an experience - you don’t test them, you don’t lecture them and you don’t force them. Instead, you create an environment where willing, caring individuals can find an experience that changes them."_ [Seth Godin](https://medium.com/swlh/will-this-be-on-the-test-237ae9cc53b4)

I know all of you are taking this class because you want to learn this topic. However, I also know that everyone always has a lot going on and it's hard to stay on track without the right mix of incentives and threats (carrots and sticks). I'm trying to create a class setup which has the right mix of such carrots and sticks.

The carrots are the perceived rewards you get from mastering the material. You might hope that achieving the learning objectives of this course  will help you with your research, prepare you for success in a future job, satisfy your intellectual curiosity, or a mix of those. If you don't hope to gain anything from the course, you shouldn't take it. 

Still, while you might have general enthusiasm for the material, keeping up with it week by week just based on this enthusiasm gets hard. That's why the occasional sticks are useful, too. Deadlines keep you on schedule, grades hopefully motivate you to do things. Balancing carrots and sticks is tricky. I prefer as many rewards as possible and keeping the threats low. 

What does the whole 'carrot and stick' discussion mean for this course?

* I expect you to be self-motivated and committed to the material and class, and put in the effort needed to succeed.

* I will try to maximize the rewards you get by hopefully teaching useful material and trying (through online interactions) to help you learn as much as possible material that is directly useful and rewarding to you.

* I will try to to provide you with a good balance of carrots and sticks to make it doable for you to commit your effort to this class.

* The environment for this class strives to be motivating and non-threatening. As such, I'll make you work hard, and expect you to do the assigned tasks by the deadlines, but in the end, I usually don't grade hard - unless you fail to keep up your end of the agreement and don't put in the work.

* This class is 'open everything'. You can use the internet, ask your classmates, myself and others, get help from wherever you can. I trust you will find the right balance of getting help when you need it while still putting in enough effort to experience real learning. 

* I will not perform any 'policing' to try to prevent you from taking shortcuts (i.e. not doing work yourself). The class contains graded assessments with deadlines, but those are meant to _help you_ stay on track. If you somehow cheat - and cheating will be easy - you are mainly cheating yourself out of learning. I hope you realize that this is pointless and defeats the purpose of why you take the class.


# Course Logistics
This section contains a lot of the boring, but still very important logistical details. It explains how the class is structured, what you are expected to do, what assessments you will get, etc.


## Course Structure
* The course is split into different units, which I call modules. Each module will usually be covered in a week.
* Each module consists of one or several assignments, which are documents containing a mix of reading things I wrote, reading things by others, watching some videos, doing some exercises, etc. 
* Each module has assessments (i.e. things you need to do for which you are graded).
* Due dates for assignments are sometime during the week of the module, either in the middle or end.
* Assigments and assessments related to the class project will occur throughout the whole semester.
* A schedule outlining the content (as it's currently planned) is on the course website.


## Module structure
* Each module contains one or several documents with readings and exercises. At times, those documents have links to videos embedded.
* All documents are hosted on a Shiny server (you don't need to know what that is) and can be accessed online through your browser. 


## Assessments 
* Your grade is made up of 2 components: The homework (50%) and a course long project (50%).
* Each module contains instructions for the homework assessment. It's a combination of exercises, quizzes and discussion contributions. Detailed information is provided for each module.
* The _Syllabus_ document contains general class information.


## Course Tools
This is a brief overview of the tools we will be using for this class. The next unit, which you can and should start right after finishing this one, describes all these tools in more detail and gives instructions on how to set them all up.

* We will use the `R` software in this course.
* We will also use RStudio (a graphical frontend to R) and Github.
* We will use a lot of tools available within R/Rstudio, such as Rmarkdown and related features.
* We will use Git/Github for the final projects and to share course materials.
* We will use eLC for quizzes.
* We will use Slack for discussions and help.
* We will use an online server to access exercises.
* We will spend this and next week setting up all the required tools.

## Further Information
* Check out all the material online.
* Most material is not yet available, it will be added/unlocked as the course proceeds.


## Introducing Ourselves
* A bit about yourself
* Your background, training, research interests
* What kind of statistics, programming, data analysis experience do you have?
* Why did you register for this course, what do you hope to learn?
* At least one interesting personal fact about you


_(schedule is subject to change)_


## Homework
* For each module/week, you will have homework to be finished by Monday __before__ we start the module in class.
* To do the homework, log into eLC and work through all the content for the module for a given week.

__The pre-class preparation/homework is a major part of the course. Expect to spend _at a minimum_ between 5-10h per week working on it!__



## Course Overview
* This course is about applied analysis of "real world" data
* We'll discuss the whole data analysis workflow 
* We'll (briefly) discuss specific modern data analysis approaches
* You can request topics (or ask me to do more/less on specific topics)



## Course Resources
We'll be drawing on a lot of different resources. For convenience, most of them are listed on the _Resources_ section of the class website. I might list additional resources for specific topics.


## More comments
* This class is cross-listed as EPID/BIOS 8060. Which section you chose shouldn't matter.
* Depending on final class size, we might be moving to B.S. Miller Hall (or not).
* I hope this course is going to be interactive. Please participate, ask questions, etc. 

__The more you engage in the course, the more you'll get out of it.__

## Next steps
* Work through all the content for module 1 "Introduction to the Topic and Project" - finish by Monday night.
* As soon as possible, start with content for module 2 - the practice sessions are lengthy!



