---
title: Markdown and colleagues
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_depth: 3
---


# Overview
In this module, you will learn the concept of reproducible research, why it is important and helpful to build your analyses in a reproducible manner, and what tools within R you can use to implement an automated, reproducible workflow.


# Learning Objectives
*	Know the concept and importance of reproducible research
*	Know how to implement reproducible research with R

# Reproducibility in Science

A hallmark of proper scientific research is that findings can be replicated/reproduced. Unfortunately, it is often the case these days that results can't be replicated/reproduced by independent investigators/labs. Sometimes, even the same labs can't reproduce their previous findings. While sometimes there is fraud, most often there are more benign reasons preventing reproducibility.

This video provides a short discussion of some of the current problems with reproducibility in science:
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/VcgO2v3JjCU" frameborder="0" allowfullscreen></iframe>
</p>


# Reproducibility of Analyses

It's hard and expensive to replicate/reproduce a full study, including all data collection, thus not routinely possible. It is easier to make sure the analysis part can be reproduced. Making the analysis easily reproducible doesn't ensure the analysis is correct. However, it allows others to take a look at analyses, redo them, and thus more quickly spot and correct potential problems. 

To allow anyone to fully reproduce an analysis, all data and code need to be provided, and the generation of results (figures and tables) needs to be fully automated. The scientific community is moving toward more reproducibility and transparency (e.g. mandating public access to data, computer code, etc.). An increasing number of funding agencies and journals require access to data and code.

While there is strong movement toward _Open Access_, providing all the data is not always possible. Full automation of data processing, analysis and result generation is however always possible, and we will use this approach.  

In this video, [Roger Peng](http://www.biostat.jhsph.edu/~rpeng/) goes into some more details of the concept of reproducible research:

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/DfBSiOupI1I" frameborder="0" allowfullscreen></iframe>
</p>

**Note the concept of mixing text and code that Roger Peng talks about.**

Roger Peng has additional videos related to reproducible research, [a playlist of those videos can be found here.](https://www.youtube.com/playlist?list=PLjTlxb-wKvXOU4WW4p3qc4VKWTI4gLNUf)


# How to do a reproducible analysis

Most importantly and fundamentally, __document everything__.

Do all processing and analysis in a scripted and well documented manner. That means no Excel, no manual copy & paste, no manual figure and table generation. All of these actions are not scripted or documented and as such not reproducible.

Some further things to pay attention are the use of open standards (open data standards, open source software), recording of software versions used, time-stamping data, and setting a random number seed in your code.

A reproducible analysis should also be _practically reproducible_ not just _theoretically_. By that I mean if you provide code, but the code only runs on some specific computer system you used, then it's not really reproducible for others. So while providing all data and code is a good first step, your goal should also be to make reproducibility easy for both the original producer of the results and the persons trying to reproduce.


# Why reproducibility is good for you
A reproducible analysis is automated. That can save you a lot of time. Initially, it seems that doing your analysis in a reproducible and automated manner takes more time and is more difficult, because you have to learn some new tools. That is true. However, once you are used to it, you will be much more efficient. Consider the case where you had some data in Excel, moved it into SAS to do an analysis and make some raw figures, opened them in Photoshop and spend a few hours making them look good. Then you or your collaborators realize that some of the data that should have been included in the analysis was not (or some data should not have been included). You need to re-create the raw figure and re-work it in Photoshop, likely spending a good bit of time. If you had an automated analysis, you could just press one (or a few) buttons and re-run everything. Also, automation makes it less likely that errors occur from copying data and intermediate results between programs. The case-study in the introductory unit is such an example, where everything was fully automated.

Making an analysis reproducible also means you to document all your steps and what you do well. This not only helps others, but your _future you_ will be very thankful. As analyses get more complex, the importance of documenting the process increases.


# Tools for reproducible analysis
Reproducible and automated analysis used to be a good bit of extra work. This is not the case anymore. R, Github and related tools have made it fairly easy to set up a reproducible workflow. While there are different tools and programming languages that allow reproducible research (e.g. Jupyter notebooks in Python, Mathematica notebooks, Sweave, Latex), we will focus on one stack of tools, namely (R)markdown & Co.

## Markdown
Markdown is a language/platform that allows you to write nice looking documents easily. The idea is that you write plain text documents with simple formatting, and then turn them into a lot of different output formats, e.g. HTML, PDF, Word, slides. You can apply layout and styling to those documents, which is done separately from the content. This means you can quickly switch between outputs. In our flow, the software in the background that turns our text documents into different formats is called [Pandoc](https://pandoc.org/). The good thing is, you really don't need to care, it all happens (almost always) behind the scences.


## R Markdown & Co
The folks from Rstudio developed [R Markdown](http://rmarkdown.rstudio.com/). This allows you to combine R code with Markdown text. You can write a single Rmarkdown (Rmd) document which contains code and text. You then `knit` the document, which uses an R package called `knitr`, runs the code, produces results and turns everything into a markdown (md) document, then using the `rmarkdown` package and `pandoc` turns this into some output format of your choice, e.g. an html or pdf or Word or Powerpoint document. Again, most of the time this happens without you needing to care about the details of this process. There are by now [a lot of different output formats](https://rmarkdown.rstudio.com/formats.html) that R Markdown supports. As an example, this whole course is written in Rmarkdown and [lives on GitHub](https://github.com/andreashandel/MADAcourse). You can copy all files and completley reproduce this course.

Note that if you want to produce pdf output, you need to have a (La)TeX system installed. It's a free typesetting system that is a bit similar to markdown, but more complicated and more powerful. I recommend [MiKTeX](https://miktex.org/) for Windows and [MacTeX ](http://www.tug.org/mactex/) for Mac. We don't absolutely need it for the class, but it's good to have and free, so I suggest you go ahead and install it.

One great thing about R Markdown is that it's well documented. The [R Studio R Markdown site](https://rmarkdown.rstudio.com/) and the [R Markdown book](https://bookdown.org/yihui/rmarkdown/) are great resources. Another good source targeted at scientists is the online book [R Markdown for Scientists](https://rmd4sci.njtierney.com/).

After developing knitr and R Markdown, [Yihui Xie](https://yihui.name/en/) and colleagues have developed several other versions of the tool. There is [bookdown](https://bookdown.org/yihui/bookdown/) which lets you nicely add references and write full books and scientific manuscripts (see the research example in the introductory lesson and a list of books written in bookdown on the [bookdown website](https://bookdown.org/)) and [blogdown](https://bookdown.org/yihui/blogdown/) which lets you make webpages (see e.g. [my group webpage which is done that way](http://handelgroup.uga.edu/)). 

The whole R Markdown/Markdown/pandoc system has become incredibly flexible and powerful and we'll use it exclusively in this class.

## Github
We discuss Github separately, see that document. Since it controls and tracks any changes you make, and works nicely with collaborators, it is a great tool for reproducible work. 

## Reference Management

This isn't really related to reproducible research, but I'm placing it here since it is one of the tools we need for this course, most importantly for the class project. 

For almost any data analysis, especially if it is meant for publication in the academic literature, you will have to cite other people's work and thus include references in your work. I assume you are familiar with how citing references works and hopefully you are already using a reference manager. While a program like Endnote is an ok reference manager, to have something that plays well with R Markdown, you need references in a format called `bibtex`. This is essentially a large file of structured plain text. You don't really ever want to edit the bibtex file yourself, instead for that you use a reference manager that is bibtex friendly. I mostly use [Jabref](http://www.jabref.org/), [Zotero](https://www.zotero.org/) is another good one. Both are free. You could probably even use Endnote. The important part is that you need to be able to save or export your references as a `bibtex` file.

To use references in your R Markdown file, specify the name and location of your `bibtex` file in the YAML header. You can also specify a CSL style file there. This is a file which controls how the references are formatted. Styles for almost any journal [are available for download here](https://www.zotero.org/styles). When you create your `bibtex` file, each reference gets a key, which is a shorthand that is generated by the reference manager or you can create yourself. For instance I use a format of lower-case first author follwed by 2 digit year for each reference, as needed with additional `a,b,c...` added. For instance for a paper that I wrote as 1st author in 2010, my bibtex key might be `handel10` or `handel10a`. You can decide what scheme to use, just pick one and use it _forever_. In your markdown document, you can then cite the reference by adding the key, such as `...in the paper by Handel et al [@handel10]...`When you knit the markdown file, it looks for a reference with the specified tag in your `bibtex` file and places all references at the end of your document using the formatting you specified.  

Some more details on citations and references in Markdown [can be found here](
https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html). The template files for the project also contain an example which you can use as starting point.


