---
title: Data Analysis Structure Assessment
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---



# Module Assessments

Make sure you've gone through all the content for this module.

## Quiz

Do the quiz for this module on eLC. The quiz consists of around 5-10 fairly easy questions. It is timed, so you need to have gone through the material and either remember some of the main items or at least remember where you saw it so you can look it up quickly.


## Exercise

While the exercise for this module does not directly deal with data analysis workflow and structure, it introduces you to some more Github functionality, a tool that you have probably figured out by now is a great component of any good a reproducible project. Specifically, we will be looking at the concept of _Issues_. The exercise is called [Github Issues](./Exercise_Github_Issues.html).

**Note that part of this exercise is due by Wednesday evening.**