---
title: Getting Data
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Overview

For this unit, we will discuss how to get different types of data into R.


# Objectives

*	Know how to get data into R



## Data import in R
* [R for Data Science](http://r4ds.had.co.nz/index.html), chapters 5 and 11.


## Some basic types of data in R
* Characters/strings. Anything can be a character, but you want to re-code as factor/numeric if applicable.
* Factors: That's what R calls categorical variables. They can be ordered or not.
* Double/integer: Numeric values that are either integers or any other numeric value (double).

## Some data structures in R
* A vector: a collection of elements in a single row or column. A single vector can contain only one element type.
* A matrix: a collection of elements in rows and columns. A matrix can contain only one element type.
* **A data frame: a collection of elements in rows and columns. Data frames can contain elements  different types.**
* A list: A combination of any of the other formats nested within each other (e.g. a vector of data frames).

# Getting data

## Data Sources
* You collected it yourself
    * Possibly very good quality and ideally suited to answer your question
    * Takes long, can be expensive
* A collaborator collected it
    * Might have been collected to answer a different question than you want to ask
    * You can ask clarification questions
* Publicly available
    * A lot of that kind of data is available
    * Explanation of data collection and possible adjustments is not always good
    * Can't always ask for clarification

## Getting the data
* Get data in 'as raw' a form as possible.
* Document when/where/how you obtained it. 
* Sometimes data comes from multiple sources, that is ok but should all be documented.
* Make a copy and use that copy for cleaning, analysis, etc.
* Do not alter the raw data!

## Getting data into R
* Download from the internet
    * download.file()
* Reading text files (tables) into R
    * read.table(), read.csv(), readr package
* Reading Excel files into R
    * Option 1: Open in Excel, save as CSV (better for reproducibility)
    * Option 2: read.xlsx() from the xlsx package (other packages exist)

* R can read many other file/data types using specific packages.

* Reading proprietary data (e.g. SAS) doesn't always work too well. Sometimes better to export the data in SAS/SPSS/etc. as CSV/TSV and then read into R.


## Checking the data
* Sometimes, the data reads properly on the 1st try
* Often, you need to adjust settings in the function that reads the data
    * Data might not read, and you get an error message
    * You don't get an error message but data looks wrong
    * Data reads ok, but the variable types are not right

After reading data, always check the data to make sure it looks as you expect it to look.


#