---
title: MADA – Spring 2023 – Syllabus
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
output: 
  html_document:
    toc_depth: 3
---

## Course Description

This course provides a survey of modern statistical approaches to analyze data. We will cover a variety of modern approaches for analyzing and interpreting data commonly encountered in public health, biomedical sciences, and related areas. This is an applied, hands-on class. We will use real data (bring your own data if you have it) to learn different methods of analysis. We will discuss all the steps of a data analysis, including obtaining and cleaning data, exploratory and full analysis, and presentation of results.

We will discuss how to formulate scientifically solid questions for a given set of data, how to decide on the right method of analysis, how to implement the analysis in R, and how to present and communicate the results. We will cover statistical topics such as regression, tree based models, cross-validation, bootstrapping, and model selection. 

## Course Learning Objectives

The main goal for this course is for you to learn the whole process of performing a data analysis project. This starts with identifying a suitable question-data pair, proceeds to getting, cleaning and exploring the data, culminates with fitting statistical models and producing materials that communicate what you did and found. A second goal is to introduce you to some modern analysis approaches that these days often go by the name of 'Machine Learning'. Finally, a related goal is to introduce you to a set of tools that allow for a modern, reproducible workflow of your analysis.

The specific learning objectives that I hope you will achieve by going through this course are:

_Define meaningful data analysis questions and assess the feasibility of answering these questions with the available data._

* Given a data set, define the questions that can be answered and formulate and implement suitable analytic approaches.
* Given a data analysis question, determine the type of data and analytic approach needed to answer it.


_Be able to obtain, organize and process data for detailed analysis._

* Know how to obtain data from a variety of different sources.
* Be knowledgeable about data types and standards and how to process them.
* Be able to organize and process data in a reproducible, automated and documented manner.
* Be able to thoughtfully and critically assess strengths and weaknesses of specific data sets and process the data appropriately.

_Be knowledgeable of different data analysis methods and select the appropriate approach for a given project based on data and question._

* Critically compare and evaluate the strengths and weaknesses of different data analysis approaches. 
* Judge the appropriateness of different approaches for specific questions and data sets and know how to apply an appropriate analytic approach.
* Design and implement successful data analyses using state-of-the-art analysis software to translate data to information and knowledge that leads to actionable insights.

_Efficiently communicate results from data analyses to a variety of stakeholders._

* Summarize analysis results in ways that provide actionable conclusions and that are easily understandable by different audiences, such as laypersons, decision makers, and expert colleagues.
* Assess the strengths and weaknesses of different formats for representing the results of data analyses.

_Use modern coding and analysis tools to implement automated, reproducible analysis and project management workflows._

* Explain the importance of workflow, project management, and reproducibility tools, and know how to use those tools.
* Be proficient in R coding to implement and execute a complete data analysis project in a reproducible and automated manner.
* Be comfortable using R and Github to do data analysis in a reproducible manner.
* Be able to quickly learn how to use new software and tools, figure out how to get help when stuck, and make it work for you.

_Develop skills to critically assess your own and others' analyses and conclusions._

* Judge the usefulness and appropriateness of data analyses described in the primary research literature.
* Learn to _look over your shoulder_ and critically assess what you are doing, what assumptions you make by doing certain things, and if and how you can justify these.



## Prerequisites


_Formal requirement for the course is BIOS 7010. Knowledge of material from BIOS 7010 is assumed. If your lack pre-requisites prevent you from enrolling in this course, please contact me to get permission to enroll._

This is a quantitative course. We will not discuss the mathematical details of specific data analysis approaches, however some statistical background and being comfortable with quantitative thinking are needed. Knowledge of statistics at the level of fitting linear or logistic models to data (e.g., as obtained in our BIOS 7010 and 7020 courses) are assumed. Some R coding skills (e.g., as obtained in our EPID 7500 class), are helpful. 

If you do not have any coding or statistics knowledge, you can still take the class, but you need to be prepared to spend extra time and effort to fill any gaps. This will be especially true for the R coding part. Some of you likely have previous R experience, while others might have little to none. If you are in the _little to none_ category, expect to spend extra time getting up to speed. I believe it's doable and worth the effort, but you need to be prepared for it. There will be plenty of help from myself, classmates, and the internet if you end up getting stuck with some of the coding, but your effort and commitment are still required.

**To re-emphasize: For those among you who have not used R or any other programming language before, this course will be time-consuming. Budget your time accordingly and plan ahead! If you do, I'm fairly certain you will find it worth it. If you are not able or willing to allot the time needed to learn enough R (and GitHub) to make things work, this course might not be ideal for you.**



## Course Setup

This course is a fully online, asynchronous, cohort-based course. That means there are weekly deadlines, but other than the fixed deadlines, you can do the work whenever it is convenient for you. 

All course materials are freely available online. We will make use of several freely available textbooks and other materials. All course materials are listed on the course website. We will use the R software for data analysis. We will also use a few other software tools. All are freely available. 

**This course is very hands-on. The weekly exercises (aka homework) are usually quite in-depth and also often time-consuming. Plan accordingly.** For each exercise, I will provide detailed instructions that hopefully make it clear what you need to do. The materials provided on the course website are not meant to be memorized, but to be used to be able to do the hands-on activities, such as the exercises and the class project.

For more details on course logistics, see the other information in the _General Information_ section of the course website.




## Grading

The grade will be made up as follows:

* 20% quizzes
* 30% exercises/homework
* 10% participation/discussions
* 40% a course long project, broken up into pieces. 

The following grading scale will be used, final grades might be curved (upward, never down): A 93-100, A- 90-93, B+ 87-90, B 83-87, B- 80-83, C+ 77-80, C 73-77, C- 70-73, D 60-70, F < 60

More detailed descriptions of the different assessments is provided on the [_Assessments page_](./Course_Assessments.html).

## Class Attendance, Make-up Policy

This class is online. You are expected to submit all assignments by their due dates. Excused misses of due dates are only provided by prior agreement with the instructor or for special reasons (medical, etc.).


## Getting Help

If you have questions about any aspect of the course, please do not hesitate to ask for help. The course materials describe in detail the ways you can ask for help.


## University Honor Code and Academic Honesty Policy

All academic work must meet the standards contained in _A Culture of Honesty_. All students are responsible to inform themselves about those standards before performing any academic work. More detailed information about academic honesty can be found at: http://www.uga.edu/honesty/

Discussions with your classmates and the instructor are encouraged. However, the final work should be your own.


## Students with Disabilities

Students with disabilities who require reasonable accommodations in order to participate in course activities or meet course requirements should contact the instructor.

## General Disclaimers

This syllabus is a general plan, deviations announced to the class by the instructor may be necessary.

## Course Outline

For an outline of the course, please see the [_Course Schedule_](./Course_Schedule.html) document. 


## More Details

The _General Information_ section and the introductory unit of this course contains all the logistic details you need to know.