---
title: Course Assessments - Overview 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---


## Assessments overview

Each module comes with assessments. Those are things you need to do that will be graded. In general, expect that each module contains **a Quiz, an Exercise, and a Discussion**. Sometimes there are additional/alternative components, such as submission of project parts.

Due dates are usually Friday 5 pm the week of the module. Some might be at other times, e.g., the beginning or middle of the week. See the schedule or the module specific assessment document. If unclear, ask.

The assessments are meant as a help for you, consider them gentle prods to ensure you work through and learn the course material. It is very easy to take shortcuts (cheat) for any of the assessments. Our academic honesty policy prohibits you from doing so. More importantly, if you take shortcuts by e.g. getting answers from a classmate, you are only hurting your own learning. I encourage getting help from any source you can, including your classmates. I let you decide how much helping each other is acceptable and at what point it turns into having someone else do the work for you that you should be doing yourself.   


## Quizzes

The quizzes cover the basics and ensures you have gone through some of the material. Each quiz consists of around 10-20 short questions. Not all answers to the quiz questions are directly found in the materials, sometimes you need to do a - hopefully straightforward - online search.

**Before submitting any quizzes, you need to set up a password using the Google Form created for that purpose. See the __Announcements Slack Channel__ for the link.**

**Unless otherwise specified, you can submit each quiz once, and it needs to be submitted by the deadline (generally Fridays), otherwise the system will not take your submission.**


### Quiz sheets

For each module, you are asked to fill out an Excel sheet with questions related to the course material. Download the quiz files from the links below, fill in the "Answer" column, and submit [to this website](https://shiny.ovpr.uga.edu/MADA2021/) by the deadline specified in the __Schedule__ document.

Unless otherwise noted, you have one submission attempt. For the first module, so you can get used to the system, you have 2 attempts.

**You can expand and resize the columns/rows of the Excel file so you can make sure to see all content. Other than that, please only fill in the _Answer_ column and don't make other changes (e.g. don't rename or delete rows/columns). If you do make changes, submission might fail. If that happens and you get an error message during submission, simply come back here, download a fresh sheet and copy and paste your answers into it, making sure to not change any other part of the sheet.** 


* [Module 1 – Course and tools introduction](./quizsheets/mada_course_tools_student.xlsx) - you have 2 attempts available for this one.
* [Module 2 – Data analysis introduction ](./quizsheets/mada_data_analysis_intro_student.xlsx)
* [Module 3 – R coding basics](./quizsheets/mada_coding_basics_student.xlsx)
* [Module 4 – Contemplating, finding and wrangling data](./quizsheets/mada_data_finding_wrangling_student.xlsx)
* [Module 5 – Visualization](./quizsheets/mada_visualization_student.xlsx)
* [Module 6 – Exploration](./quizsheets/mada_data_exploration_student.xlsx)
* [Module 7 – Statistical Analysis Overview](./quizsheets/mada_statistical_analysis_overview_student.xlsx)





### Quiz grading

Quizzes are auto-graded on submission based on a simple counting of the right answers. At the end, I'll average across all quizzes. 

Note that since there are >10 quizzes and all quizzes together count for only a fraction of the total grade, each quiz counts for a small part of your grade. 


## Exercises

The exercises are usually quite in-depth, require you to apply some of the material, and are really the main means of learning the material. For each exercise, I will provide detailed instructions that hopefully make it clear what you need to do. 

If you get stuck during the exercises (quite possible), do feel free to get help. Use the various course materials, the course discussion board as well as outside resources. But do try to do as much as possible yourself (of course with the help of Google). 

__Unless otherwise specified, exercises are due by Friday. Quite often, some part of the exercise needs to be done before that deadline to allow for group work.__ 


### Exercise grading

I grade the exercises based on 4 categories: 

* 3 points = complete or only minor omissions/mistakes.
* 2 points = some noticeable bits are missing or wrong.
* 1 points = some parts are present, but overall very incomplete.
* 0 points = completely or almost completely missing.

At my discretion, I might consider assignments even if they are submitted after the deadline. In that case, I might take off a point for lateness.

Don't interpret these scores as grades, I just use them to differentiate, then I'll adjust at the end when I compute the overall project score.


## Discussions 

We can't have in-class discussions in an online course, but hopefully we can still have robust discussions as part of the course. I hope that lively online discussions will allow us to create a sense of class community that usually comes more naturally in an in-class course. I want everyone to feel like they are part of a class, a community of students learning together, instead of just being on their own interacting with the course in front of a computer screen. To achieve that, having a lot of discussion activity is vital.

You will be asked to participate in discussions throughout the course, and discussion participation is part of the grade. The discussions are meant to connect the module content to the broader context and hopefully will spark interesting further thoughts and insights. 

__Unless otherwise specified, the first posting of the discussion is due by Wednesday, the discussion replies are due by Friday. Post to the discussion channel for the applicable module (e.g. module2_discussion, module3_discussion).__ 


### Discussion guidelines

To make sure discussions work well for everyone, here are some general guidelines.

* You can and will be asked to both start new threads/posts or reply to others. If you start a new topic, make sure you are in the right channel. (If needed, you can also move posts to other channels later). 
* You are encouraged to include links to additional material that you find online, including but not limited to research papers, or sources like Wikipedia, and other useful resources. There are no rules on formatting other than that it should be readable.
* You don't always have to provide references/links to resources, nor do you need to be sure that 'you got it right'. It's ok to post speculations/ruminations/thoughts occasionally.
* Make meaningful contributions. You are welcome to react to each others' posts with `r emo::ji("smiley")` or `r emo::ji("thumbs up")`, but that does not replace more substantial responses. Give reasons why you think something is one way or another.
* For the purpose of assessment, you need to participate in the discussions at the level specified in each module's assessment document. I encourage you to engage in further discussions. Those further posts won't be counted toward the requirement for a given module but will factor into the overall participation portion of the grade.
* It should be obvious that any posts should be helpful and civilized. I will remove any posts that are demeaning or otherwise inappropriate. Please let me know if you see such posts. 
* Discussions will remain available for the whole course, and you can keep contributing at any time.  



### Discussion grading

For most modules, you'll have to do the following (unless specifically directed otherwise):

* You need to write a post (generally a few hundred words) as instructed. Post it to the appropriate channel by __Wednesday evening__. 
* You need to write __at least__ 3 replies to posts from classmates. Those can be replies to 3 different posts or multiple back-and-forth (of substance) for the same post/thread. You must post your replies by __Friday evening__. 
* For each module (i.e. each week) you need to post a **minimum** of 4 posts (1 initial, 3 replies) with around 500 _meaningful_ words total by the deadlines. I won't count words (unless it looks really short), and probably also won't count the number of posts, unless both seem well below the minimum.
* I will use the same 0-3 point score for each discussion as for the quizzes.
* Going above the minimum (more posts, longer contributions, especially thoughtful, etc.) will count positively toward the participation portion of the final grade.
* For each module, the assessment document contains specific discussion instructions. If the specific discussion instructions are different than the general ones here, you should follow the specific ones.


## Projects

See the __Projects__ section on the website for more information.