---
title: Course Communications
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r as.Date(file.mtime(knitr::current_input()))`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc: FALSE
---


```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```



# Communication tools

## Slack

The main mode of communication will be through Slack. You should get an email invite to the Slack workspace for this class. It will go to your official UGA email and you need to use that email to sign up. If you haven't received an email by August 20, or if you added the class late, let me know so I can send you an invite. We won't use eLC, everything is going to happen on Slack or this website. 

If you are unfamiliar with Slack, it is essentially a chat/discussion tool. The main area for the class is called a _workspace_ in Slack. Ours is called __MADA-2021__. If you use Slack for other purposes, you might have additional workspaces. Each of them is independent. Inside the workspace are _channels_. Each _channel_ corresponds to a topic. The names and descriptions of the different channels should be self-explanatory. 

You need to be a member of a channel to see and participate in the channel discussion. If a channel is public, you can see it and join by clicking on the + symbol next to channels and go to 'browse channels'. Sometimes channels are private, then only those invited can participate. When I create new channels, I try to remember to add everyone by default, but it might be useful to check occasionally if there are channels which you are not a member of but would like to be.

If you have requests for specific channels to be created, let me know.

Inside a channel, you can write messages. To respond to someone's message, you can type your message just below the previous one. The good thing with this is that everyone sees it easily. The bad thing is that if there are a good number of messages being typed, it can be hard to figure out which ones go together. An alternative, and maybe better way is to reply in a thread.   

You can also use Slack to send one or more individuals direct messages. You can use that to communicate with me or each other.

Overall, Slack is fairly intuitive, and hopefully much easier to use than the rather clunky discussion feature of eLC. But some features might need getting used to. If you have not previous Slack experience, I suggest you browse through [their starter tutorials](https://slack.com/resources/slack-101) to pick up a few more tips and tricks.

**I will use the _announcements_ channel in Slack to post any important course related announcements. Check regularly.**

Use Slack widely to ask questions, to answer others' questions, to notify me and others of things that are unclear/wrong, to post links to interesting resources, etc. I hope we can use Slack  to build a _community of learners_ where you help and support each other. So please don't always wait for me to answer questions or provide feedback! Engage with each other. I will regularly visit and read the discussions and participate, but I hope that I will end up as one participant of many, not the only person providing answers.

I prefer that you use Slack instead of email to ask questions. The reason is that if you have a question, it is likely that others have it too. By asking and answering online, everyone can see it. That said, there might be instances where the question only relates to you. In such cases, feel free to either send me a direct message on Slack or email me. 


## GitHub

We will also use Github for some specific communications, related to exercises and projects. We have a separate GitHub 

. I will provide more detailed instructions on that will be provided.


## eLC

We will not be using eLC. I might occasionally use the _email everyone_ feature in eLC to send out an email to the class in the first few weeks until everyone has settled into using Slack. After that, I do not plan on using eLC much. I don't plan on posting any materials to eLC, they will all be on this website, or for confidential information, in our group Slack workspace.


## Zoom

I will offer weekly synchronous meetings through Zoom. Those are **completely optional.** Once a week I will start a Zoom meeting. Whoever wants to join can do so, and we will use the meeting for discussions, answering questions, and whatever else you want to talk about. Think of those meetings a bit like virtual office hours or virtual in-class discussions. To ensure everyone will be able to join at least occasionally, I plan to alternate between two times each week. 

Tentative dates for Zoom meetings are listed in the _Schedule_ document. Those are subject to change. If we need to move things around, I'll let you know on Slack and also update the _Schedule_ document. At the designated times, I will start the meeting. I'll wait around for 15 minutes. If nobody connects, I'll end the meeting. If people connect, we'll talk until we covered everything, or until I or you need to move on to our next appointments. The information for the Zoom meeting login will be provided on Slack.

And of course, if you have something you want to discuss outside of those scheduled times, send me a message and we can schedule a meeting.



# Discussion Guidelines

We can't have in-class discussions in an online course, but hopefully we can still have robust discussions as part of the course. You will be asked to participate continuously in discussions for the duration of the course, and discussion participation is part of the grade.

I hope that lively online discussions will allow us to create a sense of class community that usually comes more naturally in an in-class course. I want everyone to feel like they are part of a class, a community of students learning together, instead of just being on their own interacting with the course in front of a computer screen. To achieve that, having a lot of discussion activity is vital.

To make sure discussions work well for everyone, here are some general guidelines.

* You can and will be asked to both start new threads/posts or reply to others. If you start a new topic, make sure you are in the right channel. (If needed, you can also move posts to other channels later). 
* You are encouraged to include links to additional material that you find online, including but not limited to research papers, sources like CDC or Wikipedia, and other useful resources. There are no rules on formatting other than that it should be readable.
* You don't always have to provide references/links to resources, nor do you need to be sure that 'you got it right'. It's ok to post speculations/ruminations/thoughts occasionally.
* Make meaningful contributions. You are welcome to react to each others' posts with `r emo::ji("smiley")` or `r emo::ji("thumbs up")`, but that does not replace more substantial responses. Give reasons why you think something is one way or another.
* For the purpose of assessment, you need to participate in the discussions at the level specified in each module's assessment document. I encourage you to engage in further discussions. Those further posts won't be counted toward the requirement for a given module but will factor into the overall participation portion of the grade.
* It should be obvious that any posts should be helpful and civilized. I will remove any posts that are demeaning or otherwise inappropriate. Please let me know if you see such posts. 


# Discussion Assessment

For most modules, you'll have to do the following (unless specifically directed otherwise):

* You need to write a post (of at least several hundred words) as an answer to the weekly question/task. Post it into the appropriate channel by __Wednesday evening__. 
* You need to write __at least__ 3 replies to posts from classmates. Those can be replies to 3 different posts or multiple back-and-forth (of substance) for the same post/thread. You must post your replies by __Friday evening__. 
* For each module (i.e. each week) you need to post a minimum of 4 posts (1 initial, 3 replies) with around 500 _meaningful_ words total by the deadlines. I won't count words (unless it looks really short), but I will count the number of posts and check if they have been posted before/by the deadline.
* Doing the required posts (quantity, quality, and timing) will give a 100 for this module's discussion. Any shortcomings will lead to fewer points. If you don't post anything or it's all after the deadlines, it's zero points. In the end, all scores are averaged and contribute to the discussion portion of the grade.
* Going above the minimum (more posts, longer contributions, especially thoughtful, etc.) will count positively toward the participation portion of the final grade.
* For each module, the assessment document contains specific discussion instructions. If the specific discussion instructions are different than the general ones here, you should follow the specific ones.
* Discussions will remain available for the whole course, and you can keep contributing at any time.  



