---
title: MADA – Fall 2021 – Schedule
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc: FALSE
---

This is the current course schedule for the class. Things might change, so check regularly for updates.


The _Assessments_ column lists items that need to be submitted and that will be graded. Those are described in more detail in an [__Assessments__](./Course_Assessments.html) page and in the assessment document for each module. 

__Unless otherwise specified, submission deadline is the module end date (Friday) 5pm.__ 


| **Module Topic**   | **Start and end dates** | **Assessments** |
| --- | --- | --- | --- |
| Module 1 – Course and tools introduction | 8/18 – 8/27 | quiz, exercise, discussion |
| Module 2 – Data analysis introduction  | 8/30 – 9/3 | quiz, exercise, discussion |
| Module 3 – R coding basics | 9/6 – 9/10 | quiz, exercise, discussion  |
| Module 4 – Contemplating and getting data | 9/13 – 9/17 | quiz, exercise, discussion, project part 1|
| Module 5 – Visualizing data | 9/20 – 9/24 | quiz, exercise, discussion  |
| Module 6 – Wrangling and exploring data | 9/27 – 10/1 | quiz, exercise, discussion  |
| Module 7 – Statistical analysis introduction  | 10/4 – 10/8 | quiz, exercise, discussion  |
| Module 8 – Fitting basic models | 10/11 – 10/15 | quiz, exercise, discussion  |
| Module 9 – Before and after the fitting | 10/18 – 10/22 | quiz, exercise, discussion  |
| Module 10 – Subset selection and regularization | 10/25 – 10/29 | quiz, exercise, discussion  |
| Module 11 – Parameter tuning & tree-based models | 11/1 – 11/5 | quiz, exercise, discussion  |
| Module 12 – Machine learning introduction | 11/8 – 11/12 | quiz, exercise, discussion  |
| Module 13 – Revisiting the complete data analysis workflow | 11/15 – 11/19 | quiz, exercise, discussion  |
| Finishing Project | 11/22 – 11/26 (fall break part of the week) | project part 4 due Monday 11/29, 9am | 
| Project Reviews | 11/29 – 11/3 | project reviews | 
| Final project submission  | 12/10 |  project part 5 |
| Module 14 – AI & deep learning introduction | none | none - this module is optional material |


<!-- _old schedule_ -->

<!-- | **Module Topic**   | **Start and end dates** | **External Sources** | **Assessments** | -->
<!-- | --- | --- | --- | --- | -->
<!-- | Module 1 – Course and tools introduction | 8/14 – 8/23 | IDS:1,2,39,40, HGR, R4DS:27,29,30| quiz, introducing ourselves exercise | -->
<!-- | Module 2 – Topic introduction | 8/14 – 8/23 | none | quiz, discussion| -->
<!-- | Module 3 – R basics | 8/14 – 8/30 | RP:Basics, IDS:3,4 | quiz, coding exercise  | -->
<!-- | Module 4 – Data analysis overview | 9/2 – 9/6 | R4DS:1, ADS:1-4,9-11 | quiz, github issues exercise **(part due Wed)**  | -->
<!-- | Module 5 – Pondering and getting data | 9/9 – 9/13 | R4DS:14-16, IDS:6,24-27  | quiz, project part 1 | -->
<!-- | Module 6 – Data wrangling & Tidyverse | 9/16 – 9/20 |RP:WorkData,TidyData, R4DS:12,  IDS:5,21,22,23 |quiz, tidyverse exercise | -->
<!-- | Module 7 – Visualization | 9/23 – 9/27 | IDS:7-11, RP:Visualize, R4DS:3,7,28 | quiz, visualization exercise | -->
<!-- | Module 8 – Pre-processing | **9/23 – 9/27** | HMLR:3, FES | **none** | -->
<!-- | Module 9 – Model fitting overview | 9/30 – 10/4 | ISL:1,2.1, R4DS:22-23, HMLR:1 | quiz, TidyTuesday 1 exercise | -->
<!-- | Module 10 – Model assessment | 10/7 – 10/11 | HMLR:2, IDS:28,30, ISRL:5 | quiz, project part 2 | -->
<!-- | Module 11 – Basic models | 10/14 – 10/18 | HMLR:4,5,7,8 | data analysis exercise | -->
<!-- | Module 12 – Subset selection and regularization | 10/21 – 10/25 | ISLR:6 | quiz, variable selection exercise   | -->
<!-- | Module 13 – Parameter tuning & tree-based models | 10/28 – 11/1 | ISLR:8, HMLR:9-12  | tree fitting exercise   | -->
<!-- | Module 14 – More machine learning models & model interpretation | 11/4 – 11/8 | see text references | project part 3 | -->
<!-- | Module 15 – Revisiting the complete data analysis workflow | 11/11 – 11/15 | none | TidyTuesday 2 exercise (optional) | -->
<!-- | Module 16 – Deep learning, AI and Big Data | 11/18 – 11/22 | HMLR:13 | deep learning exercise (optional) | -->
<!-- | Finishing Project | 11/25 – 11/29 (fall break part of the week) | none | project part 4 | -->
<!-- | Project Reviews | 12/2 – 12/6 | none | project reviews | -->
<!-- | Final project submission  | 12/11 | none | project part 5 | -->


## Synchronous Zoom meetings

I will offer **completely optional** Zoom meetings. See the _Communication_ section for some more details. You can find the Zoom link on Slack. The current plan is to have **one Zoom meeting per module on Thursdays, alternating between 8am (odd modules) and 3pm (even modules).** (That means, most of the time, one meeting per week, unless a module is longer than a week, as it is for the first one.)

Hopefully, one of those two times works for everyone, allowing people to join at least every other time if they want. If you already know that neither times work for you, and you are keen on joining the Zoom meetings, let me know and we can adjust.

**The first Zoom session will be on Thursday, 8/19 at 3pm ET.**

