---
title: Coding Exercise
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Overview

This project asks you to write a bit of code to do a simple data analysis, we'll be using both some commands from base R and from the tidyverse, so we can compare and contrast. We'll also be using the Github workflow, so we can practice that one some more.


# Project setup
* Go to the class organization [Github website](https://github.com/epid8060fall2019) and create a new repository (press the green _New_ button) named _YOURNAME-coding_. You can leave the description empty. Choose if you want the repository to be private or public. Check the box _Initialize this repository with a README_. Set the _.gitignore_ option to `R`, you can leave the license at _none_. We won't make this exercise into a website, so we can skip all the things about _Github pages_ we did in the _Introducing Ourselves_ exercise.
* Clone the repository to your local computer (using Gitkraken or whatever software/method you decided to use for this). I recommend placing the repository inside the folder you made for the class. **Make sure you do not stick Github repositories inside other repositories, that can lead to Github breaking**. And remember that repository folders should not be synced with some other software (e.g. Dropbpox).
* Open RStudio on your computer. Choose _File_, _New Project_, _Existing Directory_ and then choose as directory the location on your computer where you cloned your repository in the previous step. If things work, you should see in the bottom right window of RStudio (at least) 2 files, one with .Rproj ending and a README.md. 
* Just to practice, let's update the Readme file. Click to open the README.md file. Replace the text with something else, e.g. "YOURNAME first R coding exercise" or something of that type. It doesn't matter what you write exactly, we are just practicing editing the Readme file.


# R content creation

_It is best to call things which store values `objects` and use `variable` for a data variable, i.e. usually a column. However, it is common to refer to things that store values as `variable` as well. Because of that, I sometimes use that terminology inadvertently too. So if I talk about variable, you need to determine from the context if I mean a certain variable in the data, i.e. a predictor variable, or a variable in R that stores some content, i.e. an object._


## Getting started
* We'll use an R Notebook for this exercise. It is a type of R Markdown document, you can [learn more here](https://bookdown.org/yihui/rmarkdown/notebook.html). Choose _File_, _New File_, _R Notebook_. A new file shows up. Read through the provided information, then delete all but the YAML header. Give it a title like _YOURNAME Coding Exercise_. Now you are ready to write some R code!
* **Remember to put a lot of commentary into your code/file! As a rule of thumb, I suggest around half of what you write should be comments explaining what you do and why. This is very helpful especially as you start learning to write code. And it makes it much easier for your future selves and others to follow.**

## Loading and checking data
* We'll look at and play with some data from the [`dslabs` package](https://simplystatistics.org/2018/01/22/the-dslabs-package-provides-datasets-for-teaching-data-science/). Write a code chunk that installs and loads the package.
* We'll look at the `gapminder` dataset from `dslabs`. Write a code chunk that pulls up the help page for the data to see what it contains. Then use the `str` and `summary` commands to take a look at the data. Use the `class` function to check what type of object this is.

## Processing data
* Using _base R notation_ (no `dplyr` allowed yet), assign only the African countries to a new object/variable called `africadata`. Run `str` and `summary` on the new object you created. You should now have 2907 observations, down from 10545. You might also notice that all different factor categories are still kept in the `continent` (and other) variables, but show 0. R does not automatically remove levels of factors even if they are empty. We don't have to worry about that just now, but something to keep in mind, it can sometimes lead to strange behavior.
* Again using _base R notation_, take the `africadata` object and make 2 new variables (name them whatever you want), one that contains only `infant_mortality` and `life_expectancy` and onethat contains only `population` and `life_expectancy`. You should have 2 new objects/variables with 2907 rows and 2 columns. Use the `str` and `summary` commands tp take a look at both variables.

## Plotting
* Using the new variables you created, plot life expectancy as a function of infant mortality and as a function of population size. Make 2 separate plots. Use base R plot commands, i.e. the `plot` function. Plot the data as points. For the plot with population size on the x-axis, set this axis to a log scale.

You should see a negative correlation between infant mortality and life expectancy. That one makes sense. You should also see a positive correlation between population size and life expectancy. In both plots, especially the 2nd one, you will see 'streaks' of data that seem to go together. Can you figure out what is going on here? Take another look at the `africadata` data we generated, which should give you a hint of what's happening. 


## More data processing
* I'm sure you realized that the pattern we see in the data is due to the fact that we have different years for individual countries, and that over time these countries increase in population size and also life expectancy. Let's pick only one year and see what patterns we find there. We want a year for which we have the most data. You might have noticed that in `africadata`, there are 226 NA (i.e. missing values) for infant mortality. Write some base R code that figures out what the corresponding years are for which infant mortality data is missing. You should find that there is missing up to 1981 and then again for 2016. So we'll avoid those years and go with 2000 instead.
* Let's create a new object by extracting only year 2000 from the `africadata` object. You should end up with 51 observations and 9 variables.


## More plotting
* Let's use base R plotting again and do the same 2 plots again, this time only for year 2000. We don't need to create those intermediate objects that only contained the variables we want to plot. We did that just for practice.

Based on those plots, there seems to still be a negative correlation between infant mortality and life expectancy, and no noticeable correlation between population size and life expectancy. Let's apply some statistics to that.

## A simple fit
* Use the `lm` function and fit life expectancy as outcome, and either infant mortality or population size as predictor. Save the result from the fit into 2 objects (e.g. `fit1` and `fit2`) and apply the `summary` command to both, which will print various fit results to the screen. Based on the p-values for each fit, what do you conclude? 


## Beyond base R

So far, we written code that didn't require any additional packages. We only loaded the `dslabs` package to get the data. While one can do a lot with base R, it is at times tedious to write code. Especially for data analysis tasks, there are many packages available that make our coding lives easier. We'll use some now.

* Write code to load the `tidyverse` collection of packages and the `skimr` package. If you don't have them installed, do so. This will likely install a lot of packages and take a while.
* Use the `glimpse` function from `dplyr` and the `skim` function from the `skimr` package to look at the `gapminder` object.
* Use the `filter` and `select` functions from `dplyr` to extract only the african countries from the `gapminder` object and then keep only the variables `infant_mortality`, `life_expectancy`, `population` and `country`.
* Make 2 plots using `ggplot` for life expectancy as function of infant mortality and population. Also give each country a separate color in the plot.
* Write code that uses the gapminder object, pulls out data for africa and year 2000 and creates a `ggplot` for `life_expectancy` as function of `infant_mortality`, with a linear model fit added.   
 

# Sending updates to Github
* Once you are done with your exercise, under the `Run` menu (top left) select `Restart R and Run all Chunks`. Make sure no error messages show up.

sure the 2 files (README.md and especially index.Rmd/index.html) look the way you want. Make changes until everything works. Once you are happy with things, close RStudio. 
* Go to the program you use for Github (I will assume that it's GitKraken, if you use something else the details might vary). In the top right of Gitkraken, there should be a notification about changed files. Click _view changes_, then _Stage_. Write a commit message, commit the changes. You should see the _master_ with the computer symbol be above the one with some random logo. That means your local repository is ahead of the one on github.com. To get them in sync, you click the _push_ button. If things work, the two symbols should now be in the same line.
* Go back to github.com and to your repository website. Click the link that you added to your Readme file, which should bring you to your new introductory website. [Here is mine as an example](https://epid8060fall2019.github.io/andreashandel-introduction/).


