---
title: Introduction Assessment 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

# Module Assessments

Each module comes with an assessment. Those are things you need to do that will be graded.

In general, expect that each module contains **a Quiz, an Exercise, and a Discussion**. Sometimes there are additional/alternative components, such as submission of project parts.

The idea is that the quiz covers the basics and ensures you have gone through some of the material. The exercise requires you to apply some of the material. In general, the exercise will be the most time-consuming. Each exercise has a different format. It should always be clear what you need to do. The discussion is meant to connect the module content to the broader context and hopefully will spark interesting further thoughts and insights. 


## Quiz

Get the quiz sheet from the _Course Resources_ section. Fill it in, then submit to the online grading system before the deadline. 


## Exercise




## Discussion 

Look online and find an example of a research project that provides (or claims to provide) all materials to allow reproduction of results, similar to Brian's project I shared with you. If you are able, download the materials and see if you can reproduce things. Report the project you found and your experience reproducing it in the _Reproducible Project Examples_ channel. I suggest you focus on projects that are done with our set of tools (R/Rmarkdown, etc.). Post your finding.

As I was looking for examples for this course, I found it surprisingly difficult to find research projects that were _fully and fairly easily_ reproducible. I didn't find a single one "out there" that seemed both complete and easy enough to point to it. Often the projects only provided data or code to reproduce some parts, and usually, the setup and effort required were significant. I'm curious to see if you can find some projects that are easy to reproduce and that provide the required information to reproduce the majority of results.

