---
title: "Example Template for Data Analysis Project Report"
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: TRUE 
---

# Summary/Abstract
_Write a summary of your project._


# Introduction

## General Background Information
_Provide enough background on your topic that others can understand the why and how of your analysis_ 

## Description of data and data source
_Give an overview of what the data is, what it contains, where it's from, etc._

## Questions/Hypotheses to be addressed
_State the research questions you plan to answer with this analysis_



#Methods 
_Note that in a research paper, this section is often (too) short. Here, you need to provide everything to allow full reproducibiliy for the reader._


##Data aquisition
_As applicable, explain where and how you got the data. If you directly import the data from an online source, you can combine this section with the next._

##Data import and cleaning
_Write code that reads in the file and cleans it (some) so it's ready for exploratory analysis._


##Exploratory Analysis
_Use a combination of text output and figures to explore your data. As you do so and find issues with your data (e.g. wrong entries, need to convert variables to different types, etc.), continue cleaning the data._

###Exploration of outcome
_Use graphical and non-graphical approaches to get a good understanding of any variable you plan to use as outcome in your analysis_

###Exploration of main predictor/exposure
_If you have one or several predictor variables that you are especially interested in, explore them here_

###Exploration of other predictors
_Look at other predictors of interest, their relation to the outcome and to each other_


##Further Pre-processing
_Further clean and process your data to ready it for final analysis. This can involve steps such as removing any NA values, making sure all variables are coded properly (factors, numeric, etc.), collinear and/or near-zero variance variables are removed, etc. The specific steps taken will depend on the method you use in your formal analysis._


##Formal analysis
_Perform your formal analysis using a suitable statistical/machine learning method._


##Final results
_Produce meaningful figures, tables, etc for your final results._

#Discussion

##Summary and Interpretation
_Discuss what you did and what you found_

##Strengths and Limitations
_Discuss what you perceive as strengths and limitations of your analysis._

##Conclusions
_What's the take-home message?_

