---
title: Class Project Information 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

_Some of this will only fully make sense once we are a few weeks into the course. It's nevertheless a good idea to read through it and get an overall idea before we have discussed all the different tools and details mentioned. Re-visit/re-read as needed._

# Overview
A semester long data analysis project will be a major method of assessment for this class. The project should include all the different components of a data analysis we will cover in this class.

* Finding a good data - question pair
* Getting the data
* Cleaning the data
* Exploring the data
* Processing the data
* Analyzing the data
* Reporting/communicating your findings
* Doing everything reproducibly


# Timeline
There are several deadlines throughout the course at which time you need to submit parts of your project

* Part 1: Have a question/hypothesis & suitable data. 
* Part 2: Part 1 + and exploratory/univariate analysis. 
* Part 3: Part 2 + bivariate analysis.
* Part 4: Parts 3 + full analysis.
* Part 5: Updated final report based on feedback.

The deadlines are listed in the _Schedule_ document (it's unlikely, but they might change, so keep checking that document).



# Feedback and Assessment
You will receive feedback from me and/or your classmates after each submission. 

* I will provide feedback on parts 1-3. 
* Some of your classmates will provide peer-review on part 4. Details on that will be provided in a separate document, posted to the _Project_ section of the website.
* Part 5 is the final submission. 

I will assess parts 1-3, mainly checking to see that you deliver what you were supposed to and got the project to the requested stage. I will also assess your _peer reviews_ for part 4. Those portions are about 25% of the _project grade._ The final submission will count for the remaining 75%. 


# Project Requirements
You can pick your project topic and data source pretty much however you like. The only requirements are:

* Real world (messy) data.
* An interesting question.
* An analysis that has not been done previously.
* A fully reproducible and automated analysis using the tools we use in this class.

# Data sources
You can use data from any source you like, herer are some possible ones.

## Your "own" data
If you have data that you are using for some research project(s) you are doing, you are welcome and encouraged to work on this as part of the class project. Of course, what you do for this class project needs to be new work, not a previously done and recycled analysis. Also, since the analysis needs to be fully reproducible, you need to provide the data at least within the class (no need to make it publicly available).

## Publicly available data
You can use any data you can get access to. Since it needs to be reproducible, you need to be able to share the data at least with me and the classmates who will review your project.

I have a [list of data sources I maintain (contributions welcome)](https://github.com/ahgroup/research-and-teaching-resource-lists/blob/master/Data_Resources.md). Of course you are not limited to data listed there.

_Often, the most interesting questions can be asked by combining data from more than one source._


# Logistics and formatting
Each assignment needs to be submitted in a fully reproducible form. You should create a Github repository which should contain all the files for your project. Name it `YOURNAME-project`. You can create it as public or private repository within the course organization.

The main document should be an Rmarkdown (or bookdown) file, which can be turned into a suitable output format (html or word or pdf). I suggest having the output be a word document, since that is what most journals want for submission of a scientific paper. The template I provide is set up for word output. However, if you for instance decide to include interactive figures or apps (using e.g. Shiny) in your analysis project, you can also pick html as output. If for some reason you want/need pdf, that's ok too.

I recommend structuring your project similar to the provided template and the structure we will cover in class, with data, scripts, results and manuscript in different folders, various R scripts to perform different bits of the analysis, and a final Rmd file that pulls everything in and generates the report. However, as long as it makes sense and allows easy reproducibility, you can structure your project as you like. 

For all your submissions, you need to provide everything needed (data, code, etc.) to all full and automated reproduction of your analysis.

Your report should be more detailed than what would normally go into a peer reviewed paper. Include parts such as results from your exploratory analysis. Those can be part of the main document or if you prefer a separate supplementary document.

References should be included as a bibtex file and cited in the Rmd file. See the template for an example.

# Project template

I created [a public Github repository called dataanalyis-template](https://github.com/andreashandel/dataanalysis-template) which is meant as a template for doing a data analysis project. It has different folders for organizing your project. Various readme files are provided to explain what each folder should contain. The template also contains several example files to show how the whole project workflow (or any data analysis workflow for that matter) can work. 

Inside the `manuscript` folder, there is a R Markdown template file with a suggested outline for the report write-up. I have also indicated which sections need to be completed/filled for which part of the project. This template is just a guide, you do not have to follow exactly that structure, as long as you provide all the requested parts for the the different submission deadlines and a final, complete, fully automated and reproducible project, with all files in one github repository, at the end.

In addition to the Rmd file, there is a bibliography file in bibtex format which contains the references, and a style file which indicates reference formatting. You can use it as starting point. Feel free to switch the reference formatting style.

I highly recommend you use this template as starting point for your project. To use the template for your class project, go [its Github repository](https://github.com/andreashandel/dataanalysis-template) and follow the instructions to turn it into a new repository for your class project, call it `YOURNAME-project`. Create the repository inside the class organization. To do so, choose the class organization as the owner of the repository. This also allows you to make it a private repository if you want to (e.g. if you have data you do not want to be public). Once you made the new repository, follow the usual Github workflow to get it to your local computer. Then open the readme file and change the text so it states somewhere "This is YOURNAME class project repository".


# Project communications 
Any communication regarding this project should happen in the _Class Project_ discussion board. Go there to ask project-specific questions, to post links to your repository whenever you have a part finished, etc. I will also post any further or clarifying information there.

