---
title: Tidyverse and Friends 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---



# Overview

One of the strengths of R (and also a source of confusion) is that it is very flexible and almost always lets you do things in more than one way. 
R itself comes with some functionality. This is often referred to as `base R`. Even with just this basic functionality, there are often many ways to accomplish a task. But the real power of R comes from its many packages. Packages (also called libraries in some other programming languages) contain additional functions and functionality that lets you fairly easily do things that would require a ton of coding effort if you tried to do it yourself. Someone basically wrote the functionality for you, and you can use it.

While there are tons of packages available, some are very commonly used. For data analysis tasks, the folks from R Studio have developed many packages that are very useful. One such set of packages, the most widely used set, is called the [`tidyverse`](https://www.tidyverse.org/). By using those packages, a lot of coding applied to data analysis becomes easier, more readable, and more powerful. We will use the `tidyverse` packages and their functionality a lot. That said, knowing some base R is very useful. In general, you can fairly easily mix and match. 

# Learning Objectives
* Know what the `tidyverse` is
* Be able to apply `tidyverse` code to data wrangling problems
* Be able to use R packages for specific needs



# Tidy data

The concept of the tidyverse can be traced back to the concept of _tidy data_, which [Hadley Wickham](http://hadley.nz/) introduced in [this article](https://www.jstatsoft.org/article/view/v059i10/). Give the article a quick read to get the overall idea. You will see it a lot, so it's good to be familiar with it. 


# Tidyverse philosophy 

The R packages developed by Hadley and others were eventually grouped together and now goes by the name "tidyverse". If you want to learn more about the principles of those packages, [you can read this short manifesto](https://tidyverse.tidyverse.org/articles/manifesto.html) written by Hadley. Some of what he writes might not be fully understandable to you (e.g., functional programming or pipes), but you'll get the overall idea. For our purpose, the important aspects to remember is that the tidyverse is a collection of R packages that are all structured similarly (from a user perspective), play nice with each other, and help you in your various analysis tasks as you go from messy data to data that is tidied up and ready for formal analysis.

Note that there are many more R packages that are not part of the core tidyverse, but that still follow the same principles and nicely work with other tidyverse packages.


# Learning the Tidyverse 

To learn more and practice some of the tidyverse functionality, I suggest you go through the _Work with Data_ and _Tidy your Data_ sections of the [R Studio primers](https://rstudio.cloud/learn/primers/). More or less the same content, presented a bit differently and non-interactively, can be found in the [_Tidy data_ chapter in R4DS](https://r4ds.had.co.nz/tidy-data.html). This might be a good reference to look up things. If you want to practice and learn more, read the  _tidyverse_, _Introduction to data wrangling_, _Reshaping data_ and _Joining tables_ chapters of [IDS](https://rafalab.github.io/dsbook/). If you want some more data tyding practice, check out [this tutorial by Garrett Grolemund](http://garrettgman.github.io/tidying/) or [this short blog post by Joachim Goedhart](https://thenode.biologists.com/converting-excellent-spreadsheets-tidy-data/education/). 

These are a lot of resources, and I don't expect you to work through all of them in detail. I do suggest you take a quick look at all of them, and then work through some of them based on your knowledge level. As we progress through the course and you are asked to do a lot of these tasks, you will likely want to re-visit these materials. And as always, Google is your friend.


# Beyond the Tidyverse

There are lots of other useful R packages that make your coding life easier. We'll make liberal use of them throughout this course. It is highly likely that for some of the course exercises or the course project, you will be using other packages that you find helpful. Being able to find packages that do what you need is important. 

The quality of packages varies. In general, if they are on `CRAN` or `bioconductor`, they are reasonably stable. Any packages that involve RStudio, or are otherwise widely used and have many developers, suggests that things are tested fairly well. Other packages might be more experimental, and while they might work well, there might also be bugs. So always carefully inspect the results you get to make sure things are reliable. 



