---
title: MADA Fall 2019 - Some teaching and learning thoughts
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

# Introduction
Over the last few years, I have gotten quite interested in figuring out what works best for teaching and learning, especially in an online setting. I'm describing a few of my thoughts here and invite you to engage in this as an _unrelated side topic_.

**This document is not directly related to the course topic and completely optional. If you have no interest in contemplating best teaching and learning practices, feel free to skip over this document and ignore anything further on this topic throughout the course, it won't affect your grade at all.**



# General teaching and learning thoughts

When I was a student, I never found lectures very useful. Real learning for me only happened when I had to engage with the material. The inferiority of lectures compared to other ways of teaching and learning is increasingly supported by solid evidence from the field of education research. I am trying to move away from lecturing as much as possible and towards modes and activities that maximize learning. Overall, it seems to me learning is best when these conditions are met:

* __Relevance:__ As a student, the material I was supposed to learn needed to be relevant to me, either for something as basic as solving a homework problem, or something more substantial.  For example, I knew I wanted to learn the topic because it was useful for something I wanted to accomplish in my work/life.

* __Right level of challenge:__ Any assignment that consisted of mindlessly following recipes and clicking buttons (hello, undergrad physics and chemistry labs!) does not seem to help me much in learning. Assignments needed to have a certain level of difficulty to ensure the brain is sufficiently engaged.

* __Right level of freedom and constraints:__ Similar to the level of difficulty, the level of freedom given for specific exercises and assignments is important. If things are too constraint, things become boring, rote and not much real learning - other than going through the motions - is achieved. I used to think it was best to give as much freedom as possible. However, I have learned that this often makes learners feel lost and directionless. Thus, some level of constraint in the form of structures and guidance seems helpful. For instance, for the class project, I'm providing you with a template. This is not meant to constrain you unnecessarily, but instead to provide some hopefully helpful structure. In general, if you want to do things differently or your own way in this class, I'm completely ok with that as long as your way of doing it produces results that are at least as good as the way I suggest.

* __Right level of "carrots and sticks":__ This is similar to the freedom and constraints one. In most classes I teach, including this one, I can assume that students take the class because you want to learn the topic. However, I also know everyone has a lot going on, and it's hard to stay on track without the right mix of incentives and consequences (carrots and sticks). I'm trying to create a class setup which has the right combination of such carrots and sticks.  The carrots are the perceived rewards you get from mastering the material. (If you don't hope to gain anything from the course, you shouldn't take it.) You might hope that achieving the learning objectives of this course will help you with your research, prepare you for success in a future job, satisfy your intellectual curiosity, or a mix of those. I'm hopeful the class can deliver those rewards for you. Still, while you might have a general enthusiasm for the material, keeping up with it week by week just based on this enthusiasm gets hard. That's why the occasional sticks are useful, too. Deadlines keep you on schedule, and grades hopefully motivate you to do things. Balancing carrots and sticks is tricky. I prefer as many rewards as possible and keeping the consequences low. But I know that many small assignments are important to stay on track, especially for an online class. Thus the many small quizzes and the different parts for the project.

* __Support and Community:__ Receiving the right level of support from others, especially instructor(s) and peers. Too much help hinders learning, but too little leads to frustration and thus also reduced learning. Having a community of learners that at the same time, challenges each other and helps each other is ideal for learning. This is generally easier to achieve in a classroom setting. Online courses are challenging in that respect. I'm still trying to figure out how to best structure things to encourage a great and supportive community of learners in an online setting.


My dream class is one that operates as described in this quote by Seth Godin:

_"If you want people to become passionate, engaged in a field, transformed by an experience - you don’t test them, you don’t lecture them and you don’t force them. Instead, you create an environment where willing, caring individuals can find an experience that changes them."_ [Seth Godin](https://medium.com/swlh/will-this-be-on-the-test-237ae9cc53b4)

Getting that right for a specific audience, especially in an online class, is not easy. Thus, the following request for your feedback/participation.


# Teaching and learning course discussions
For anyone interested, I would like to engage you in a discussion of best practices in teaching and learning (online) in general and for this course specifically. To that end, I made a discussion board on eLC. We'll start with a single discussion board called "Teaching and Learning". If we need more or other venues, we can add. For those interested, I'd also be happy to post some of the resources I've found/read over the last few years. Let me know in the discussion board if you want any (and on what topic).

My hope is that those of you interested in the topic will post there anything of relevance. That could be feedback on specific class activities that you found especially useful or useless in learning a topic. If you found anything was either 'too little' or 'too much' based on the categories I list above, I would like to hear that. Also, if you have any good materials to share, new activities to suggest, best practices from your own teaching experience, etc. I'd love to hear about it and discuss it.

If at any point in the course you feel that you are not learning optimally, let me know and tell me why - and ideally what would be required for optimal learning. I know I can't _make_ students learn, but I can try to provide the best environment possible for learning to happen, and I'm trying to figure out how to do that.

**Again, participation in such side-discussions on this topic is completely voluntary, won't affect your grade - even if you tell me that most exercises suck. In fact, if you explain why they suck (and how to make them better), I'm more than happy to give you bonus points  `r emo::ji('smiley')`**.