---
title: The Tidyverse 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```


# Overview
In this module, we will learn about a set of packages in R commonly refered to as the [tidyverse](). These packages add a lot of powerful functionality to R that makes coding often much easier, especially for data analysis related tasks.



# Learning Objectives

# The tidyverse

One of the strengths of R (and also a source of confusion) is that it is very flexible and almost always lets you do things in more than one way. The assignments above mostly introduced ways to interact with R that is sometimes called `base R`. This refers to the fact that you can do all the operations with what is directly built into R. But a lot of the power in R comes from its packages. Over the last few years, a group of individuals has developed (many) packages that make especially data analysis easier. One such set of packages, the most widely used one, is called the [`tidyverse`](https://www.tidyverse.org/). By using those packages, a lot of coding applied to data analysis becomes easier, more readable and more powerful. In this course, we will use the `tidyverse` packages and their functionality a lot. To start getting familiar with the tidyverse, read and work through [chapter 5 of IDS](https://rafalab.github.io/dsbook/tidyverse.html). 




The [RStudio tutorials](https://rstudio.cloud/learn/primers/) also have several that deal with various tidyverse functionality. We'll visit some of them at a later point, but feel free to already start exploring them.

