---
title: Github Issues Exercise
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r Sys.Date()`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
---


```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

# Overview

These exercises teach a bit more about Github, specifically how _Issues_ work. 

For some background reading, see [this Github Guide](https://guides.github.com/features/issues/).

* Go to the [course website](https://andreashandel.github.io/MADAcourse/) and find something wrong/unclear/worth improving (e.g. a typo, something confusing, a broken link, a suggestion for a new reference).
* Go to the [course Github repository](https://github.com/andreashandel/MADAcourse) and klick on _Issues_.
* Click the green _New Issue_ button and describe your issue you found. Make the title and the content as descriptive and clear as possible. Submit your issue.

Let's do it once more:

* Go to _Classlist_ on eLC. You should see a roster of students enrolled in the class. Make sure they are sorted by last name. Note the name of the student who is just below you (if you are the last student, note the 1st student's name). 
* Go to the [Github course organization](https://github.com/epid8060fall2019) and find the repository of that student containing their introduction.
* Read through their introduction. Think of something you would like to know about them in addition to what they wrote. File an _Issue_ on their repository. 
* Everyone of you should be receiving a notification that someone (the student in the class list above you) has filed an _Issue_. Go ahead and address the issue (i.e. make changes to your markdown document). Follow the workflow described in _Introducing Ourselves_ for this. Once you pushed your updates to the repository, go to the _Issues_ page, and close the issues with a comment of what you did.
* The person who initiated the issue should get a reply that the issue has been closed. You can then go and check if it has been addressed.

This _Issues_ feature is a very powerful way of working collaboratively on software. For instance if you go to the Github page of a popular R package, such as [ggplot2](https://github.com/tidyverse/ggplot2) you'll find a lot of open (and closed) issues. Take a look at some of those issues to get an idea of how they are used. It's a great way for developers of software (and other products) to learn about problems, to hear what features users want, etc. So don't feel shy about opening an issue on someone's Github project. The one thing you should make sure is to first search all the open and closed issues (and maybe a quick online search as well) to make sure it's not something that has been discussed before. 

Just for fun, here is me [filing an issue for the mlr package](https://github.com/mlr-org/mlr/issues/837). If you read through it, you'll see that based on that, the developers added the functionality I wanted `r emo::ji('smiley')`. Try that with Microsoft or any other of those software companies `r emo::ji('scream')`!



