---
title: Model Performance for Continuous Outcomes  
author:
  name: Andreas Handel
  affiliation: University of Georgia
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
    includes:
      in_header: test1.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE, exercise.cap = "SEM calculator")

```



```{r, context="render", echo=FALSE}
sliderInput("b", "Slope", min = -10, max = 10, value = 2)
sliderInput("a", "Intercept", min = -50, max = 50, value = 0)
plotOutput("fitplot")
```

```{r, context="server"}
output$fitplot <- renderPlot({
  plot(cars[,1],cars[,2],xlab = 'Car speed', ylab = 'Distance before stop', xlim=c(0,25), ylim = c(-50,150))
  abline(input$a,input$b)
  })
```


```{r manualfit, echo = FALSE}
question("Based on your manual model fit, which of the following parameter choices gives the best fitting model?",
         answer("Intercept = 0, Slope = 5", message = "These model parameters lead to a model that is systematically higher than  the data."  ),
         answer("Intercept = -50, Slope = 7", message = "This model is below the data for low x and above the data for high x."),
         answer("Intercept = 0, Slope = 3", correct = TRUE, message = "These parameter choices are closest to the data."),
         answer("Intercept = -10, Slope = 3", message = "Close, but there is another parameter combination that is even better."),
         allow_retry = TRUE
)
```


<div data-iframe-height></div>
