---
title: EPID 8060 Fall 2019 - Course and Topic Introduction Logistics
author:
  name: Andreas Handel
  affiliation: University of Georgia
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
bibliography: ../../media/references.bib
runtime: shiny_prerendered
---

## Overview
* This first unit (which in this course I call module) provides an overview of the whole course logistics and setup, followed by an overall introduction to the topic and a motivating example.

## Learning Objectives
* Know how this course is set up and what you are expected to do
* Know what this course is all about
* Get motivated toward learning and doing data science!

## Overall Course Structure
* The course is split into different units, which I call modules. Each module will be covered in a week.
* Most of the assignments (reading, videos, etc.) and assessments (exercises, quizzes, discussion) are done within a single module.
* Assigments and assessments related to the class project will occur throughout the whole semester.

## Module structure
* Each module contains

## Course Learning Objectives 

The main goal for this course is to teach the whole process of performing a data analysis project. This starts with identifying a suitable question-data pair, all the way to fitting statistical models and producing materials that communicate what you did and found. A second goal is to introduce you to some modern analysis approaches that these days often go by the name of 'Machine Learning'. Finally, a related third goal is to introduce you to a set of tools that allow for a modern, reproducible workflow of your analyis.

The specific learning objectives that I hope you will achieve by going through this course are:

* Critically compare and evaluate the strengths and weaknesses of different modern data analysis approaches, judge the appropriateness of different approaches for specific questions and data sets.
* Given a data set, define the questions that can be answered and formulate and implement suitable analytic approaches.
* Given a data science question, determine the type of data and analytic approach needed to answer it.
* Explain the importance of workflow and project management tools and reproducibility for data analysis, and know how to use those tools.
* Be knowledgeable about data types and standards and what analysis methods to apply to specific situations.
* Design and implement successful data analyses using state-of-the-art analysis software to translate data to information and knowledge that leads to actionable insights.
* Summarize analysis results in ways that provide actionable conclusions and that are easily understandable by different audiences, such as lay persons, decision makers, and expert colleagues.
* Know how to obtain, process and analyze data from a variety of different sources.


## Course Tools

* We will use the `R` software in this course.
* We will also use RStudio (a graphical frontend to R) and Github.
* We will use a lot of tools available within R/Rstudio, such as Rmarkdown and related features.
* We will spend next week to set up all the tools. Feel free to work ahead.


## Assessments 
* Your grade is made up of 2 components: The homework (50%) and a course long project (50%).
* Each module contains instructions for the homework assessment. It's a combination of short online quizzes, discussion contributions, and tracking of your progress on online exercises using DataCamp. Detailed information is provided for each module.
* The _Syllabus_ document contains general class information.


## Prerequisites

Nominally, for this course some R coding skills (e.g. as obtained in EPID 7500), as well as basic knowledge of statistics at the level of fitting linear or logistic models to data (e.g. as obtained in our BIOS 7010 and 7020 courses) are expected. If you don't have any of the pre-requisite R coding or statistics knowledge, you can still take the class, but you need to be prepared to spend some extra time and effort to fill any gaps. This will be especially true for the `R` coding part. There are likely some students in class who have pretty solid previous `R` experience, while others might have little to none. That means if you are in the latter category, expect to spend extra time getting up to speed with R. I believe it's doable and worth the effort, but you need to be prepared for it. For instance we'll spend a week on 'R Basics' - for those with good `R` knowledge, this might be a 2 hour refresher, for those with none that week might be a 20 hour committment. There will be plenty of help from myself, classmates and the internet if you end up getting stuck with some of the coding, but your effort and committment are still required.







## Further Information
* Check out all the material online.
* Most material is not yet available, it will be added/unlocked as the course proceeds.



## Today's Agenda
* Introducing ourselves
* Introducing the course 
* Introducing the project
* Starting with R

## Introducing Ourselves
* A bit about yourself
* Your background, training, research interests
* What kind of statistics, programming, data analysis experience do you have?
* Why did you register for this course, what do you hope to learn?
* At least one interesting personal fact about you

## Course Structure
* The course is split into modules. 
* Each module spans a week.
* A schedule outlining the content (as it's currently planned) is online.

_(schedule is subject to change)_


## Homework
* For each module/week, you will have homework to be finished by Monday __before__ we start the module in class.
* To do the homework, log into eLC and work through all the content for the module for a given week.

__The pre-class preparation/homework is a major part of the course. Expect to spend _at a minimum_ between 5-10h per week working on it!__

## Class Sessions
* Lecturing will be minimal. The main way you will encounter new material is through the homework.
* We will discuss whatever questions you have and topics that might not have been covered in the homework.
* The majority of time will be spent practicing data analysis.
* A good chunk of the time will be devoted to working on your projects.
* You are expected to bring your laptop to each class.


## Course Overview
* This course is about applied analysis of "real world" data
* We'll discuss the whole data analysis workflow 
* We'll (briefly) discuss specific modern data analysis approaches
* You can request topics (or ask me to do more/less on specific topics)

## Main goals for this Course
* You will understand the whole data analysis workflow/process
* You will have done one complete data analysis from beginning to end using real data.
* You will be aware of different approaches that exist to analyze data, know how they work, their advantages and disadvantages, etc.
* You will be comfortable using R to do data analysis in a reproducible manner.

We can allocate the time we spend on these different parts depending on your needs and interests. I will adjust according to your feedback.


## Course Resources
The material for the course comes from a variety of sources. My main sources are:

* [DataCamp](http://www.datacamp.com)
* ["R for Data Science" by Hadley Wickham and Garrett Grolemund](http://r4ds.had.co.nz/)
* ["Applied Predictive Modeling" by Kuhn & Johnson](http://appliedpredictivemodeling.com/)
* ["An Introduction to Statistical Learning" by James et al.](http://www-bcf.usc.edu/~gareth/ISL/)
* ["Data Science Specialization" on Coursera](https://www.coursera.org/specialization/jhudatascience/1)

All resources, apart from Kuhn & Johnson, have both a free and a paid option. Some of the material is in the general resources folder.

I will provide additional material and references for specific topics. (This is much more material than we'll cover.)


## Project Overview
A large component of your grade will be based on a project. This project should be one "complete" data analysis and include everything we'll cover in this course:

* Formulating a good data analysis question/hypothesis and pairing it with the right data
* Cleaning data and getting it into R
* Doing some preliminary data analysis
* Doing a thorough analysis of the data to answer your question
* Produce results (figures, tables)
* Write up your project as a reproducible report


## Project Timeline
The project is split into parts with different due dates (see schedule):

* Part I: Have a question/hypothesis & suitable data 
* Part II: Part I + full exploratory analysis, report draft
* Part III: Parts II + full analysis and final report
* Part IV: Updated final report based on feedback

_Each assignment needs to be submitted in a fully reproducible form._

_See 'Schedule' document for deadlines_

## Project - Next Steps 
* Start thinking about it
* Review online materials
* Find a good data - question pair
* We'll discuss a bit more next week
* I'd be happy to provide frequent feedback

## More comments
* This class is cross-listed as EPID/BIOS 8060. Which section you chose shouldn't matter.
* Depending on final class size, we might be moving to B.S. Miller Hall (or not).
* I hope this course is going to be interactive. Please participate, ask questions, etc. 

__The more you engage in the course, the more you'll get out of it.__

## For next week
* Work through all the content for module 1 "Introduction to the Topic and Project" - finish by Monday night.
* As soon as possible, start with content for module 2 - the practice sessions are lengthy!


##Overview
These videos provide some interesting discussions of the vast topic of data analysis. They are meant to be entertaining and inspiring and get you thinking about the big picture.

_Note that while you keep hearing __big__ data mentioned often, most of the time this applies to data in general._


## Introductory/general discussions of data analysis
A short personal history of data analysis.
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/na124KLSJl4" frameborder="0" allowfullscreen></iframe>
</p>

A short discussion/contemplation on what to do with data. 
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/AWPrOvzzqZk" frameborder="0" allowfullscreen></iframe>
</p>

Some interesting case studies of data analyses.
<p>
<iframe src="https://embed.ted.com/talks/sebastian_wernicke_how_to_use_data_to_make_a_hit_tv_show" width="640" height="360" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</p>

## Health related data analysis

An interesting and entertaining story of body/health data and what it can tell us:
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/_GMVTJ9ZKVc" frameborder="0" allowfullscreen></iframe>
</p>

From the 'master of public health data' - one of his entertaining and enlightening TED talks:
<p>
<iframe src="https://embed.ted.com/talks/hans_rosling_at_state" width="640" height="360" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</p>



## Optional - a few TED collections/playlists focusing on data:

[The dark side of data](http://www.ted.com/playlists/130/the_dark_side_of_data)

[Making sense of too much data](http://www.ted.com/playlists/56/making_sense_of_too_much_data)

[Art from data](http://www.ted.com/playlists/201/art_from_data)

[What your data reveals about you](http://www.ted.com/playlists/374/what_your_data_reveals_about_y)



